### ISSUE TITLE
Should story points be an integer?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#147]
currently story points are a double, as you can see in the yaml file:

```yaml
days:
- date: '2018-01-08'
  updated_at: '2018-01-08T13:27:44+01:00'
  story_points:
    total: 41.0
    open: 41.0
  tasks:
    total: 138
    open: 138
```

Can we safely change it to integer? maybe someone is using it with doubles.... 🤔
